CREATE SCHEMA IF NOT EXISTS game;

CREATE TABLE IF NOT EXISTS game.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL REFERENCES game.profiles (username) ON DELETE CASCADE,
    slot INTEGER NOT NULL,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL DEFAULT 'WARRIOR',
    gender TEXT NOT NULL DEFAULT 'M',
    appearance TEXT NOT NULL DEFAULT 'A',
    level INTEGER NOT NULL DEFAULT 1,
    stat_str INTEGER NOT NULL DEFAULT 0,
    stat_vit INTEGER NOT NULL DEFAULT 0,
    stat_dex INTEGER NOT NULL DEFAULT 0,
    stat_int INTEGER NOT NULL DEFAULT 0,
    map_key TEXT,
    local_x REAL,
    local_y REAL,
    runtime_epoch BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    CHECK (class_name IN ('WARRIOR', 'NINJA', 'SURA', 'SHAMAN')),
    CHECK (gender IN ('M', 'F')),
    CHECK (appearance IN ('A', 'B')),
    CHECK (slot >= 0 AND slot < 4)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_players_name_active
ON game.players (name)
WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_players_username_slot_active
ON game.players (username, slot)
WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_players_username
ON game.players (username);

INSERT INTO game.players (
    id,
    username,
    slot,
    name,
    class_name,
    gender,
    appearance,
    level,
    map_key,
    local_x,
    local_y
)
VALUES (1, 'admin', 0, 'Admin', 'WARRIOR', 'M', 'A', 99, 'metin2_map_c1', 480, 736),
       (2, 'guest', 0, 'Guest', 'SHAMAN', 'F', 'B', 35, 'metin2_map_c1', 480, 736)
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('game.players', 'id'),
    COALESCE((SELECT MAX(id) FROM game.players), 1),
    true
);
