# Development profile
# Usage: helm ... -f values.yaml -f values-dev.yaml

namespaceOverride: ""
profile: dev

postgres:
  service:
    type: LoadBalancer

auth:
  service:
    type: LoadBalancer
  logFilter: info,zohar_authsrv=info,zohar_db=info,sqlx::query=debug

channelGateway:
  service:
    type: LoadBalancer
  logFilter: info,zohar_gamesrv=info,zohar_db=info,sqlx::query=debug

network:
  # For service-nodeport mode, set this to a LAN-routable host IPv4.
  mapAdvertiseIp: "192.168.0.143"
  mapEndpointMode: service-nodeport

topology:
  channels:
    - id: 1
      entrypointPort: 13000

core:
  logFilter: info,zohar_core=info,zohar_gamesrv=info,zohar_db=info,zohar_net=trace,zohar_sim=debug,sqlx::query=debug
