{{- if and .Values.auth.enabled .Values.auth.token.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zohar.authTokenSecretName" . }}
  namespace: {{ include "zohar.namespace" . }}
  labels:
    {{- include "zohar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "zohar.authTokenSecretKey" . }}: {{ default "dev-secret-change-me" .Values.auth.token.secret.value | quote }}
{{- end }}
