{{- if .Values.authDatabase.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zohar.authDbSecretName" . }}
  namespace: {{ include "zohar.namespace" . }}
  labels:
    {{- include "zohar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "zohar.authDbSecretKey" . }}: {{ include "zohar.authDatabaseUrl" . | quote }}
{{- end }}
{{- if .Values.gameDatabase.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zohar.gameDbSecretName" . }}
  namespace: {{ include "zohar.namespace" . }}
  labels:
    {{- include "zohar.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "zohar.gameDbSecretKey" . }}: {{ include "zohar.gameDatabaseUrl" . | quote }}
{{- end }}
